# These settings are synced to GitHub by https://github.com/apps/settings

repository:
  # Basic settings
  name: reqwest-openai-tracing
  description: OpenTelemetry tracing middleware for OpenAI API calls made with reqwest
  topics: openai, tracing, opentelemetry, langfuse, reqwest
  private: false
  has_issues: true
  has_projects: false
  has_wiki: false
  has_downloads: true
  default_branch: main
  allow_squash_merge: true
  allow_merge_commit: true
  allow_rebase_merge: true
  delete_branch_on_merge: true
  enable_automated_security_fixes: true
  enable_vulnerability_alerts: true

# Branch protection rules
branches:
  - name: main
    # https://docs.github.com/en/rest/branches/branch-protection
    protection:
      # Require PR reviews (set to 0 for solo projects)
      required_pull_request_reviews:
        required_approving_review_count: 0
        dismiss_stale_reviews: true
        require_code_owner_reviews: false
        dismissal_restrictions: {}
      
      # Required status checks
      required_status_checks:
        strict: true  # Require branches to be up to date
        contexts:
          - "cargo test"
          - "Code Coverage"
      
      # Enforce for admins
      enforce_admins: false
      
      # Require up-to-date branches
      required_linear_history: false
      
      # Restrictions
      restrictions: null
      
      # Disallow force pushes and deletions
      allow_force_pushes: false
      allow_deletions: false
      
      # Require conversation resolution
      required_conversation_resolution: true
      
      # Lock branch (read-only)
      lock_branch: false
      
      # Allow fork syncing
      allow_fork_syncing: true