[workspace]
# Enable changelog generation
changelog_update = true
# Enable git tag creation
git_tag_enable = true
# Enable GitHub release creation
git_release_enable = true
# Customize the release name
git_release_name = "v{{version}}"
# Update dependencies during release
dependencies_update = true
# Disable registry operations for local packages
publish_allow_dirty = true
# pr_labels = ["release"] # Disabled - requires additional permissions

[[package]]
name = "reqwest-openai-tracing"
# Customize changelog if needed
changelog_path = "CHANGELOG.md"
# Set to false until async-openai is published to crates.io
# The git dependency prevents publishing
publish = false