name: Release-plz

permissions:
  pull-requests: write
  contents: write
  issues: write  # Required for adding labels to PRs

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  release-plz:
    name: Release-plz
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Get latest tag
        id: get-tag
        run: |
          # Get the latest tag, defaulting to v0.0.0 if no tags exist
          LATEST_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "v0.0.0")
          echo "Latest tag: $LATEST_TAG"
          echo "tag=$LATEST_TAG" >> $GITHUB_OUTPUT
      
      - name: Checkout previous release
        run: |
          # Clone the repo at the latest tag to use as registry manifest
          git clone . /tmp/previous-release
          cd /tmp/previous-release
          git checkout ${{ steps.get-tag.outputs.tag }}
      
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
      
      - name: Install release-plz
        uses: taiki-e/install-action@v2
        with:
          tool: release-plz
      
      - name: Run release-plz
        run: |
          release-plz release-pr \
            --git-token "${{ secrets.GITHUB_TOKEN }}" \
            --registry-manifest-path /tmp/previous-release/Cargo.toml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}